name: Update package version for release & hotfix branches

on:
  push:
    branches: [release/*, hotfix/*]

jobs:
  call_version_update:
    uses: yext/slapshot-reusable-workflows/.github/workflows/version_update.yml@main
    secrets:
      caller_github_token: ${{ secrets.GITHUB_TOKEN }}
