name: WCAG tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  call_wcag_test:
    uses: yext/slapshot-reusable-workflows/.github/workflows/wcag_test.yml@dev/mapbox-key-wcag
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
    with:
      build_script: ./tests/scripts/start-storybook.sh
